### ISSUE TITLE
Window not showing up?

### ISSUE THREAD

**Issue by florianpeninon** [abynim/Sketch-PluginHelper#1]
Hi,

I used your helper to build our own plugin and I come across a weird behavior, as soon as I change the View Controller the window isn't showing up. I tried to create exactly the same file (deleting then copy/pasting) but still no window.

Do you know what I'm doing wrong?

**Comment by abynim** [comment]
I cannot tell what the problem might be. Are you sure that the helper is being launched but the window is not showing up?

To test this, I added a new View Controller, linked it as the `window content` for the main window, and it showed up when I ran the plugin. I saved the test code in a branch here: https://github.com/abynim/Sketch-PluginHelper/tree/issue1-new-view-controller

Does the test code work for you?

**Comment by florianpeninon** [comment]
The test code doesn't work, it does what I get when I tried to do it on my own : launching because it appears in the Activity Monitor but can't see the window.

Here is what the log get me as error :

```
28/07/15 08:59:01,630   com.apple.debugserver-@(#)PROGRAM:debugserver  PROJECT:debugserver-330.0.48
[3823]  debugserver-@(#)PROGRAM:debugserver  PROJECT:debugserver-330.0.48
 for x86_64.
28/07/15 08:59:01,631   com.apple.debugserver-@(#)PROGRAM:debugserver  PROJECT:debugserver-330.0.48
[3823]  Got a connection, waiting for process information for launching or attaching.
28/07/15 08:59:01,000   kernel[0]   warning: debugserver(3823) performed out-of-band resume on PluginHelper(3822)
28/07/15 08:59:01,921   com.apple.debugserver-@(#)PROGRAM:debugserver  PROJECT:debugserver-330.0.48
[3823]  Attach succeeded, ready to debug.
28/07/15 08:59:03,657   Xcode[3707] [MT] DVTAssertions: Warning in /SourceCache/IDEFrameworks/IDEFrameworks-7720/IDEKit/Workspace/IDEToolbarStopButtonViewController.m:259
Details:  Stop Button failed to cancel tracker: 
     <IDEExecutionOperationTracker 0x7fcbb2d0f1f0 Run "PluginHelper" isFinished: YES>
     canceled: Hard Cancel
              <IDEExecutionRunnableTracker 0x7fcbaedc2b60 (null) isFinished: YES>
         canceled: Hard Cancel
         is _finishedRunning
     operationFinished: YES
         <DVTOperationGroup 0x7fcbb2f9c650 not blocking>         suboperations:
              <IDEBuildOperationGroup 0x7fcbb3e01760 not blocking>             suboperations:
                  <DVTOperation 0x7fcbb3e01130 not blocking>
                  <IDEBuildOperation 0x7fcbb01db940 not blocking>

              <DVTOperationGroup 0x7fcbaf030f70 not blocking>             suboperations:
                  <DVTOperationGroup 0x7fcbb3d40760 not blocking>                 suboperations:
                      <DVTOperation 0x7fcbb3d3ffe0 not blocking>
                      <IDESchemeActionResultOperation 0x7fcbb3d3f3e0 not blocking>
                      <IDERunOperation 0x7fcbaedc29b0 not blocking>

                  <DVTOperation 0x7fcbaf042250 not blocking>


Object:   <IDEToolbarStopButtonViewController: 0x7fcbae274370>
Method:   -_stopLaunchSession:
Thread:   <NSThread: 0x7fcbaaf38de0>{number = 1, name = main}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
```

**Comment by abynim** [comment]
@florianpnn Are you on Yosemite?

**Comment by florianpeninon** [comment]
Yes!

**Comment by abynim** [comment]
The error log shows that the error is coming from Xcode. Are you running the project in Xcode or launching it via the plugin?

The window is setup to display when the plugin-launcher file `pl.skjs` is opened, not when the helper app is run. So if you run the Xcode project, the window will not show up immediately. It will only show the window when the Sketch plugin launches the `pl.skjs` file.

If you want to show a window on launching the helper app, go to `AppDelegate.swift` and move the window initialization code from the `application(sender: NSApplication, openFile filename: String)` method to the `applicationDidFinishLaunching(aNotification: NSNotification)` method.

Can you try copying the branch into the Sketch plugins folder and then run the plugin from Sketch?

Let me know if that helps, or if my assumptions are completely wrong!

**Comment by florianpeninon** [comment]
Works!

I spent hours trying to find the solution, I didn't even think about that!
Thanks :)

**Comment by abynim** [comment]
Sweet! Now I'm really curious to see what you end up making! :)

**Comment by florianpeninon** [comment]
I'll send you a private demo, I can't publish as it would expose our Database :/

Other question : any idea how I could open a window controller based on a parameter that Sketch send?
I'm building a suite of plugin and would like to have all of them under the same OSX app.
I would like to be able to define the initWindow based on a parameter that Sketch would send, do you think it's possible or the parameters are parsed after the app is launched?

**Comment by abynim** [comment]
Oooh private demo! Sounds cool :)

To show different content based on a parameter sent from Sketch, you can load the same window but change its `contentViewController` to a different NSViewController that you instantiate from the Storyboard, based on the parameter. 

I updated the branch here with an example: https://github.com/abynim/Sketch-PluginHelper/tree/issue1-new-view-controller

In the example, look at `AppDelegate.swift`, and the two `sketchplugin` files that send different params.
